# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # - repo: https://github.com/ansible/ansible-lint.git
  #   rev: v4.2.0
  #   hooks:
  #     - id: ansible-lint
  #       # always_run: true
  #       # pass_filenames: false
  #       # files: \.(yaml|yml)$
  #       types: [yaml]
  #       # verbose: true
  #       entry: env ANSIBLE_LIBRARY=./library ansible-lint --force-color -p
  #       #entry: ansible-lint

  # - repo: https://github.com/adrienverge/yamllint.git
  #   rev: v1.20.0
  #   hooks:
  #     - id: yamllint
  #       files: \.(yaml|yml)$
  #       types: [file, yaml]
  #       entry: yamllint --strict -f parsable

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: requirements-txt-fixer
        # - id: end-of-file-fixer
        # - id: mixed-line-ending
        # - id: check-byte-order-marker
        # - id: check-executables-have-shebangs
        # - id: debug-statements
        # - id: flake8
        # - id: check-yaml
        types: [yaml]
        #files: .*\.(yaml|yml)$

        # github.com/jumanjihouse/pre-commit-hooks
        # markdownlint
        # shellcheck
        #
        # github.com/Lucas-C/pre-commit-hooks-nodejs
        # markdown-toc
        #
        # github.com/detailyang/pre-commit-shell
        # shell-lint
        #
        # github.com/bemeurer/beautysh
        # beautysh
        #
        # github.com/antonbabenko/pre-commit-terraform
        # terraform_fmt # Rewrites all Terraform configuration files to a canonical format.
        # terraform_docs # Inserts input and output documentation into README.md (using terraform-docs).
        # terraform_docs_without_aggregate_type_defaults # Inserts input and output documentation into README.md (using terraform-docs).
        # terraform_docs_replace # Overwrite content of README.md with terraform-docs.
        # terraform_validate # Validates all Terraform configuration files.
        # terraform_tflint # Validates all Terraform configuration files with TFLint.
        # terragrunt_fmt # Rewrites all Terragrunt configuration files to a canonical format.
        #
        # github.com/openstack-dev/bashate
        # bashate - This hook runs bashate for linting shell scripts
        #
        # github.com/codespell-project/codespell
        # codespell - Checks for common misspellings in text files.
        #

  - repo: https://github.com/milin/giticket
    rev: 6f166c66f2423e8e27898b39385d1166f9b643a3
    hooks:
      - id: giticket
        args: ["--regex=TOK-[0-9]", "--format={ticket} {commit_msg}"] # Optional

  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
