---
# ansible-playbook dotfiles.yml -D -t ansible_conf --ask-vault-pass

- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  roles:
    - { role : dotfiles, tags: [ 'dotfiles-role' ] }
