#!/usr/bin/env ansible-playbook mbp.yml -D --check --ask-become-pass --ask-vault-pass
---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  pre_tasks:
    - block:
        - name: mbp | Check if my_vars.yml file exists
          stat:
            path: my_vars.yml
          register: stat_result
        - name: mpb | Include my_vars.yml vars file
          include_vars:
            file: my_vars.yml
          when: stat_result.stat.exists
      tags: always

  roles:
    - { role: check-prereqs, tags: ["check-prereqs-role"] }
    - { role: hashicorp-vault, tags: ["hashicorp-vault-role"] }
    - { role: ssh, tags: ["ssh-role"] }
    - { role: python, tags: ["python-role"] }
    - { role: dotfiles, tags: ["dotfiles-role"] }
    - { role: ansible, tags: ["ansible-role"] }
    - { role: terraform, tags: ["terraform-role"] }
    - { role: aws, tags: ["aws-role"] }
    - { role: gcloud, tags: ["gcloud-role"] }
    - { role: cronjobs, tags: ["cronjobs-role"] }
    - { role: macos, tags: ["macos-role"] }
