#!/usr/bin/env ansible-playbook mbp.yml -D --check --ask-become-pass --ask-vault-pass
---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  roles:
    - { role: hashicorp-vault, tags: ["hashicorp-vault-role"] }
    - { role: dotfiles, tags: ["dotfiles-role"] }
    - { role: macos, tags: ["macos-role"] }
