---
- block:
    - name: ansible_conf | Deploy {{ home_dir }}/.ansible.cfg
      copy:
        src: ansible.cfg
        dest: "{{ home_dir }}/.ansible.cfg"
        mode: 0400
        owner: "{{ user }}"
        group: "{{ group }}"

    - set_fact:
        ANSIBLE_VAULT_PASS: "{{ lookup('lastpass', 'dotfiles/ANSIBLE_VAULT_PASS') }}"

    - name: ansible_conf | Deploy {{ home_dir }}/.vault_pass
      copy:
        content: "{{ ANSIBLE_VAULT_PASS }}"
        dest: "{{ home_dir }}/.vault_pass"
        mode: 0400
        owner: "{{ user }}"
        group: "{{ group }}"
      no_log: True

  tags: ansible_conf
