---
- block:
    - name: backup | Deploy backup scripts
      copy:
        src: "{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: 0755
      loop:
        - "ng_backup_all.sh"
        - "ng_backup_history.sh"
  tags: backup
