---
# https://codefresh-io.github.io/cli/completion/codefresh-completion/

- block:
    - name: codefresh | tap Codefresh homebrew repo
      homebrew_tap:
        name: "codefresh-io/{{ item }}"
        state: present
      when: install_packages
      loop:
        - cli
        - venona

    - name: codefresh | install Codefresh CLI
      homebrew:
        name: "{{ item }}"
        state: present
      when: install_packages
      loop:
        - codefresh
        - venona

    - set_fact:
        CODEFRESH_API_KEY: "{{ lookup('lastpass', 'dotfiles/CODEFRESH', field='API_KEY') }}"

    - name: codefresh | Deploy {{ home_dir }}/.cfconfig
      template:
        src: "codefresh_cfconfig.j2"
        dest: "{{ home_dir }}/.cfconfig"
        mode: 0600
        owner: "{{ user }}"
        group: "{{ group }}"

  tags: codefresh
