---
- block:
    - name: configs | Create {{ home_dir }}/{{ item }} dir
      file:
        path: "{{ home_dir }}/{{ item}}"
        state: directory
        mode: 0700
        owner: "{{ user }}"
        group: "{{ group }}"
      loop:
        - ".gitconfig/hooks"
        - "src"
        - "src/{{ github_work_organization }}"

    - name: configs | Deploy {{ home_dir }}/src/{{ github_work_organization }}/.gitconfig
      template:
        src: "{{ github_work_organization }}_gitconfig.j2"
        dest: "{{ home_dir }}/src/{{ github_work_organization }}/.gitconfig"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: configs | Deploy {{ home_dir }}/.gitconfig
      template:
        src: gitconfig.j2
        dest: "{{ home_dir }}/.gitconfig"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"

  tags: git
