---
- block:
    - name: python | Install pyenv
      homebrew:
        name: "{{ item }}"
        state: "present"
      when: install_packages | d() | bool
      loop:
        - "pyenv"
        - "pyenv-virtualenv"
        - "pyenv-virtualenvwrapper"

    - name: python | pyenv install python if it's not already installed
      shell: "pyenv install -s {{ python_version }}"
      args:
        chdir: "{{ home_dir }}"

    - name: python | pyenv set python global version
      shell: "pyenv global {{ python_version }}"
      args:
        chdir: "{{ home_dir }}"

  tags: python
