---
- block:
    - name: terraform | Install Terragrunt & tfenv
      homebrew:
        name: "{{ item.pkg_name }}"
        state: "present"
        install_options: "{{ item.install_options | default(omit) }}"
      loop:
        - { pkg_name: "tfenv" }
        - { pkg_name: "terragrunt", install_options: "ignore-dependencies" } # terragrunt will try to install Terraform as a dendency and will conflict with tfenv
      tags: brew_install

    - name: terraform | Create ~/.tfenv directory
      file:
        path: "~/.tfenv"
        state: directory
        mode: 0755
        owner: "{{ user }}"
        group: "{{ group }}"

    # tfenv will verify the download against Hashicorp's published sha256 hash using gpg
    - name: terraform | Deploy ~/.tfenv/use-gpgv
      copy:
        content: "trust-tfenv: yes"
        dest: ~/.tfenv/use-gpgv
        mode: 0400

    - name: terraform | Install different Terraform versions
      shell: "/usr/local/bin/tfenv install {{ item }}"
      loop:
        - "latest"
        - "latest:^0.11"
      register: cmd_result
      changed_when: '"already installed" not in cmd_result.stdout'

      # https://github.com/gruntwork-io/gruntwork-installer/releases
    - name: terraform | Install gruntwork-installer
      shell: "curl -LsS https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version v0.0.24"

      # https://github.com/gruntwork-io/kubergrunt/releases
    - name: terraform | Install kubergrunt
      shell: "gruntwork-install --binary-name kubergrunt --repo https://github.com/gruntwork-io/kubergrunt --tag v0.5.8"

  tags: terraform
