---
- block:
    - name: tmux | Create {{ home_dir }}/.tmux dir
      file:
        path: "{{ home_dir }}/.tmux"
        state: directory
        mode: 0755
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: tmux | Deploy {{ home_dir }}/.tmux.conf
      copy:
        src: tmux.conf
        dest: "{{ home_dir }}/.tmux.conf"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: tmux | Clone tmux plugins
      git:
        repo: "{{ item }}"
        dest: "~/.tmux/plugins/{{ item | basename }}"
        force: yes
        depth: 1
      loop:
        - https://github.com/tmux-plugins/tmux-yank
        - https://github.com/tmux-plugins/tmux-resurrect
        - https://github.com/tmux-plugins/tmux-continuum
        - https://github.com/tmux-plugins/tmux-sessionist
        - https://github.com/tmux-plugins/tmux-logging
        - https://github.com/tmux-plugins/tmux-open
        - https://github.com/tmux-plugins/tmux-urlview
      notify:
        - "install and update plugins"

    - name: tmux | Deploy {{ home_dir }}/.tmux/tmux-macos.conf
      copy:
        src: tmux-macos.conf
        dest: "{{ home_dir }}/.tmux/tmux-macos.conf"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: tmux | Deploy {{ home_dir }}/.tmux/devops_session.yml
      template:
        src: tmux_devops_session.yml.j2
        dest: "{{ home_dir }}/.tmux/devops_session.yml"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: tmux | Install urlview dependency for tmux-urlview plugin
      homebrew:
        name: "urlview"
        state: "present"
      when: install_packages

  tags: tmux
