---

- block:

  # required for Vim YouCompleteMe plugin to work on MacOS
  - name: vim | Install brew cmake/macvim
    homebrew:
      name: "{{ item }}"
      state: "present"
    with_items:
      - "cmake"
      - "macvim"
    tags: brew_install

  - name: vim | Deploy {{ home_dir }}/.vimrc
    copy:
      src: vimrc
      dest: "{{ home_dir }}/.vimrc"
      mode: 0644
      owner: "{{ user }}"
      group: "{{ group }}"

  tags: vim
