---

- block:

  - name: zsh | Download oh-my-zsh installer
    get_url:
      url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
      dest: /tmp/oh-my-zsh-install.sh
      mode: 0550

  - name: packages | Install oh-my-zsh
    command: "sh /tmp/oh-my-zsh-install.sh"
    args:
      creates: "{{ home_dir }}/.oh-my-zsh"

  - name: zsh | Deploy {{ home_dir }}/.zshrc
    template:
      src: "zshrc.j2"
      dest: "{{ home_dir }}/.zshrc"
      mode: 0644
      owner: "{{ user }}"
      group: "{{ group }}"

  - name: zsh | Deploy {{ home_dir }}/.fzf.zsh
    copy:
      src: "fzf.zsh"
      dest: "{{ home_dir }}/.fzf.zsh"
      mode: 0644
      owner: "{{ user }}"
      group: "{{ group }}"

  - name: zsh | Clone zsh-completions plugin repo
    git:
       repo: https://github.com/zsh-users/zsh-completions
       dest: "~/.oh-my-zsh/custom/plugins/zsh-completions"
       force: yes

  - name: zsh | Clone zsh-syntax-highlighting plugin repo
    git:
       repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
       dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
       force: yes

  tags: zsh
