---

- block:

  - name: configs | Collect only facts returned by facter
    setup:
      gather_subset:
        - '!all'
        - '!any'
        - facter

  - name: configs | Deploy {{ home_dir }}/.vimrc
    copy:
      src: vimrc
      dest: "{{ home_dir }}/.vimrc"
      mode: 0644
      owner: "{{ user }}"
      group: "{{ group }}"

  - name: configs | Deploy {{ home_dir }}/.aliases
    template:
      src: aliases.j2
      dest: "{{ home_dir }}/.aliases"
      mode: 0644
      owner: "{{ user }}"
      group: "{{ group }}"
    tags: alias

  - name: configs | Deploy {{ home_dir }}/.env
    copy:
      src: env
      dest: "{{ home_dir }}/.env"
      mode: 0644
      owner: "{{ user }}"
      group: "{{ group }}"
    tags: env

  - name: configs | Deploy {{ home_dir }}/.bashrc
    copy:
      src: bashrc
      dest: "{{ home_dir }}/.bashrc"
      mode: 0644
      owner: "{{ user }}"
      group: "{{ group }}"

  - name: configs | Deploy {{ home_dir }}/.zshrc
    template:
      src: "zshrc.j2"
      dest: "{{ home_dir }}/.zshrc"
      mode: 0644
      owner: "{{ user }}"
      group: "{{ group }}"

  - name: configs | Deploy {{ home_dir }}/.tmux.conf
    template:
      src: tmux.conf
      dest: "{{ home_dir }}/.tmux.conf"
      mode: 0644
      owner: "{{ user }}"
      group: "{{ group }}"

  - name: configs | Deploy {{ home_dir }}/.gitconfig
    template:
      src: gitconfig.j2
      dest: "{{ home_dir }}/.gitconfig"
      mode: 0644
      owner: "{{ user }}"
      group: "{{ group }}"

  tags: configs
