---

- block:

  - name: packages | Install Homebrew packages
    homebrew:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('latest') }}"
      version: "{{ item.version | default(omit) }}"
      update_homebrew: yes
    with_items: "{{ homebrew_packages }}"

  - name: packages | Install Homebrew Cask packages
    homebrew_cask:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('latest') }}"
      update_homebrew: yes
    with_items: "{{ homebrew_cask_packages }}"

  tags: packages
