---
- block:
    - name: k8s | Include brew_install.yml
      import_tasks: "../../../roles/shared/tasks/brew_install.yml"
      vars:
        brew_packages: "{{ k8s_brew_packages }}"

    - name: k8s | Include brew_install.yml
      import_tasks: "../../../roles/shared/tasks/brew_cask_install.yml"
      vars:
        brew_cask_packages: "{{ k8s_brew_cask_packages }}"

    - name: k8s | kubectl krew install starboard # noqa 305 Use shell only when shell functionality is required
      shell: "kubectl krew install starboard"
      register: cmd_result
      changed_when: '"it is already installed" not in cmd_result.stderr'

    - name: k8s | Import octant_plugins.yml
      import_tasks: "octant_plugins.yml"
  tags: k8s
