---
- block:
    - name: Ensuring Xcode Command Lines Tools are installed
      command: xcode-select -p
      changed_when: false
      register: "check_xcode_command_line_tools"

    - name: Installing Xcode Command Line Tools
      command: "xcode-select --install"
      when: check_xcode_command_line_tools is not defined

    - name: Include mac-app-store.yml
      include: mac-app-store.yml

    - name: Creates the "locate" database if it doesn't exist
      command:
        cmd: "launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist"
        creates: /var/db/locate.database
      become: yes
      become_method: sudo

    - name: Include macos-defaults.yml
      include: macos-defaults.yml

    - name: Include macos-dock
      include: macos-dock.yml
  tags: macos
