---
- block:
    - name: extras | Include brew_install.yml
      import_tasks: "../../../roles/shared/tasks/brew_install.yml"
      vars:
        brew_packages: "{{ homebrew_extras }}"
    - name: extras | Include brew_cask_install.yml
      import_tasks: "../../../roles/shared/tasks/brew_cask_install.yml"
      vars:
        brew_cask_packages: "{{ homebrew_cask_extras }}"

    - name: extras | Deploy {{ home_dir }}/.aliases.d/extras
      copy:
        src: extras_aliases
        dest: "{{ home_dir }}/.aliases.d/extras"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      tags: "aliases"
  tags: extras
