---
- block:
    - name: gcloud | Install gcloud
      community.general.homebrew_cask:
        name: google-cloud-sdk
        state: "present"
      when: install_packages | d() | bool
      tags: brew_cask_install

    - name: gcloud | Create {{ home_dir }}/.config/gcloud directories
      file:
        path: "{{ home_dir }}/.config/{{ item }}"
        state: directory
        mode: 0755
        owner: "{{ user }}"
        group: "{{ group }}"
      loop:
        - "gcloud"
        - "gcloud/configurations"
        - "gcloud/credentials"

    - name: gcloud | Deploy {{ home_dir }}/.config/gcloud/configurations/config_{{ item.project }}
      template:
        src: config.j2
        dest: "{{ home_dir }}/.config/gcloud/configurations/config_{{ item.project }}"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      loop: "{{ gcloud_configs }}"

  tags: gcloud
