---
###################
# Hashicorp Vault #
###################
vault_addr_env : 127.0.0.1
vault_port : 8200
vault_web_protocol: "http"

vault_config_dir: "/keybase/private/nicolasg7/hvault"
vault_logs_dir: "{{ vault_config_dir }}/log"
vault_data_dir: "{{ vault_config_dir }}/data"
vault_keys_dir: "{{ vault_config_dir }}/keys"

#vault_install_dir: "/usr/local/bin"
#vault_download_dir: "/tmp"
#vault_checksum_file: "vault_{{ vault_version }}_SHA256SUMS"
#vault_pkg_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
#vault_checksum_file_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version}}_SHA256SUMS"

vault_secret_engines_list_enabled:
  - aws
  - pki
  - ssh
  - totp
  - transit

auth_backends_list:
  - "aws"
  - "github"
  - "userpass"

vault_audit_backend_list:
  -  { name: 'file', options: 'file_path=/keybase/private/nicolasg7/hvault/log/audit.log' }

# vault_github_organization: "Magnetic"
# vault_github_organization_team:
#   - { team_name: 'Admins', vault_policy: 'admins' }
#   - { team_name: 'Engineering', vault_policy: 'readonly' }
